spring.application.name=iw3
# ===================================================================
# Configuración de Base de Datos MySQL
# ===================================================================
dev.info.enabled=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/iw3_prod_2026?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1u4rootiw3}